# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - '0.10'

env:
  global:
    # SAUCE_TOKENS for zuul
    - secure: ff2wtrRkjbMndn7pypwR+HAWethL+57EEy0fg+HH/kUU0/2DebyB4dXWkVSW1cotUzzAUcq9RXYYATpn7Mq+Im0UUCUEztZ7y+gccF+wPSnLd5btD1sYiFTo7/dxNAjRYIdf0ceSShs4USFhMFGs0BgFtZUjUMtb9+NZSsGAHz/5Y/uUJYEdfF6k4MWVKydDkqcX1Rqiutb+GDWoChBFBvBS50sWoB/hDCSAQxTieAqD9xu381LgrCWMLBP4iM4s7kQAPocDCvCn3s5F2UzHRR+BCuCJNS7jKq2zzokgzLW6PKib663RDCoic8+f1cNHEoEWomM1Vts9+hVKZYKURFC1h3OGpXW9Hy01NYWIvtvrrnanDCM693FOH7aYWqm28ZuWVSRgfdiya/nzypH8YDYITEI7D/bsnzgwlUa8xl2HOJ2eGJeTrGzaN0cOR2bRlnJThVuN6D+6WeMNUtKz+TurNv66hiisMIyb4l1V1zsH/mJxuQ4alRyARP1vVk6waN+mTeeHHwuehxBnwcpb9vil0g2L5XutPzysU7ZPYkQY7Fx0iz77dNO6oR+vxjeMxDlZBlPRU59lQCjXaaSq/dX4hw04LQxcEeffeN901PYOVAUsF8gp9cbpjJKoFahRrv4cKJtmKCt29cPKBXJYRUzmXZ0BnSrwZg7axEtQRQY=
    - secure: Ix/C/YDSOyMPPQsAeSSsXGmyF7wFBoNPXVJ7C+VugAw1LM2Gtr+cK0nSoqUzBWd0DyEp+AYZXper+fXanaS5d3gqC/pCJW1sNYV02VVtN+osK1nI4BCm4NKc7pcBIPcVgPzuriHo4lo8XBk8oDnDT0xJEHLYQjcSKUhtRPHPwrQ9tW7KybFh+BTqMmXbzGpQdc82c3kIKR7xVq6NJ/OjshRuYwPCc7ErwXY7lGdcMi69n5V4N3qlWHmGfiOpMfAR7TobcNjvoMhUcPEh0nxDTc4fTqkHXSIlbOk0+lZnXJmsdH4NCmVKpoAH4xEeCmzjs82woGuleJPGdSH39bvhLZ8XGZikxBtS8dHzDMpDfAQX7Ju4UsjBY1IJsQuDWZ0OGhWBA5/KV5CziJW4YGIfvA8X2kV+rlbfOLG+3ymX91XZ7YMMi6iz54T0ogtC3Agh102gbO3kovD/fANAma4I1tc5ZRZbxtNpY+wHJ393rrbU23FUgUXtmaW/d+ifDw9UTYAnkxnOA9cGFDaCH15DKYf1jcnMrunBTfK+cM5fmEDxcS6XiAmZ+SFc9NeO9WL/rLJ1Ohe4QyQDYw3FrDF8j0ARtBkWSv9cEme4PJ3Z4HjeylgDPyKyfi1Ksny5aFz2bnMKDpBBCHTjwI//yfG8lNHtYOi47bbFNwESDxpBhc8=
    # COVERALLS_REPO_TOKEN
    - secure: PxK6QzGX0e/TZoETDaV7m0MEtL8if03FfcEKfZBmApmI6mCstuD0MNxL34lNxSXnY322CddegT8I2D8U8NzJjrOyT3MJyGASzV2HstJdzspCB1WTcfKued8TFNA6kFAg5ImLZ52m+wZXwgP74RVpcddnx8+ScGwLZSt9IoIArOd6C+9u018tl7klxVNkiRbQTjrxKeP8ykH9Z6ZuEg29V7JYI+/xaz91T6uP4Qmx0GBPBo58rcxMPCFivd8327jkRTBH2hLouf59hClHrlYAbnujTFL8ofwAR3AT1JPk5SOpFwBeEZgIoXOr3ofuJS/xRPZwsIr3FanV02EJmb1ZxWn4T1hDh1r8qgND84LFsGzuLGexaOBkvcUvejKqrfN3qcaAmL3vYkriMVS7n4fTcspZPc1iquHyA7BMqP4lQEsaoKnUnYsu2vvrw/3JWZC6brE84IODjP2b5JRCNic6u6BdzMb2zXRDn/EswA2YBlikD9mzdeyIQfc/su2tJnFx5V2Hj/Py7xXMwM4HTZ83lLuNpXX5hv0GuYoAg+oJzLa0ilsfUhGwCwaBWAM3xeMUCqR94PPgppjemvmaabvPyxHI1DQbvUYM/9wU7vznKyeCRWIZHz6fkqcjo0Mf+EdnRFBElJSg/NG3+7Y4OhOjTVv22kHVP5BWMMqKJPNyJuY=

# Npm publish options
before_deploy:
  - npm install coffee-script --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: X0FT1IjseGglFZnXTb8KSo6t3H3H+Kg/9A7FImDMtBTYqN89vBICNdoRzZ42Yer3BhOlTGUAIXdNKXWC7JP8QCxN82PSGUCvE1VWYxH4L82V/mf3FB8zC5mjwQwfGU/PmePzF4q6jJTz4+fLCstcx8vbeYvBrlxFnUb5PFESGADAchqxC6YkA4d61Jag+gOkzzdRq2O8jLWanIyYL4jHe4S67ynp88n1EIEoPhGoTGf/hHI/14Ds5RopMpLz+2xFYZMdd7iDeVUYN5UM78P0qCtzxBlqPSgoncWfxwAiRwpxFlRGzQEgE8kXXuvmQuNfoSI6ahqCoG+LuNDjCbOtazp63K9FngysQxeNIUSSuVuVuRGAfBIT3ZQThO9K511OEx31YV6jKN7WxjrFONYt219E2bVeLrC4AVPAvkK7kNBsg5rz64ojedvASZyeNOHgMyeAmMFX89tD/6woypU0hvNaEmtvsFeFLUYKfq0+8YDoZY70E2ZtF/ofKBUjP/Y97YDGx4IatzDNFRAl2iVzv5sESQR6X6Pov4rE78QPDEaFqM5PWgroZFBpQcwH74UJqTYIuYA4PpbbOhZsRRQjBk7UWR7ypyeqn/Yy1qDcw8TUI2TRTHBKxIOKPBW3+7rkrfKVPtWGvk4cjgM7h/CSUbmMpKEejnBHvnnFf6dRodA=

# Cloud testing
after_deploy:
  - npm install
  - npm run test-cloud
